---

loopback: 10.255.0.5/32

bgp_fabric:
  asn: 65003
  router_id: 10.255.0.5
  neighbor:
    - {address: 10.0.255.17, remote_as: 65000}
    - {address: 10.0.255.21, remote_as: 65000}
  networks:
    - 10.255.0.5/32
    - 10.0.255.16/30
    - 10.0.255.20/30
    - 10.0.102.0/24

spanning_tree:
  mode: mstp
  disabled_vlans: 4094

mlag:
  domain_id: mlag-11
  local_interface: Vlan4094
  peer_address: 169.254.1.1
  primary_priority: 10
  peer_link: Ethernet3

vlans:
  4094:
    alias: peerlink-vlan
    pipv4: 169.254.1.2/30
    trunk_group: mlagpeer
    options: no autostate
  102:
    alias: prod-server-102
    vipv4: 10.0.102.254
    pipv4: 10.0.102.252/24

virtual_router_mac_address: 00:1c:73:00:00:99

interfaces:
  Ethernet1:
    alias: uplink-spine-1
    port_state: no switchport
    address: 10.0.255.18/30
  Ethernet2:
    alias: uplink-spine-2
    port_state: no switchport
    address: 10.0.255.22/30
  Ethernet3:
    alias: peerlink-leaf-4
    port_state: switchport mode trunk
    switchport_trunk: group mlagpeer
